version: 2
jobs:
  build:
    docker:
    - image: circleci/android:api-28-alpha
    working_directory: ~/workspace
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Chmod permissions
        command: sudo chmod +x ./gradlew
    - run: yes | sdkmanager --licenses || exit 0
    - run: yes | sdkmanager --update || exit 0
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Build debug APK and release APK
        command: |
          ./gradlew :app:assembleDebug
          ./gradlew :app:assembleDebugAndroidTest
    - run:
        name: Set Google Cloud target project
        command: gcloud config set project androiddemo-aafef
    - run:
        name: Store Google Service Account
        command: |
            echo $SERVICE_KEY > key.txt
            base64 -i key.txt -d > ${HOME}/gcloud-service-key.json
    - run:
        name: Authorize gcloud and set config defaults
        command: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
    - run:
        name: Run instrumented test on Firebase Test Lab
        command: gcloud firebase test android run --type instrumentation --app app/build/outputs/apk/debug/app-debug.apk --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk --device model=taimen,version=27,locale=en_US,orientation=portrait
    - run:
        name: Create directory to store test results
        command: mkdir firebase
    - run:
        name: Download instrumented test results from Firebase Test Lab
        command: gsutil -m cp -r -U "`gsutil ls gs://test-lab-4qr7bhv2pt0zk-h9pxpvyf9hfcm | tail -1`*" /root/workspace/firebase/
    - store_artifacts:
        path: firebase/
        destination: /firebase/